config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  
  get '/recipes', to: 'recipes#index'
  get '/recipes/new', to: 'recipes#new'
  post '/recipes/', to: 'recipes#create'
  get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  get '/recipes/edit/:id', to: 'recipes#edit', as: 'recipe_edit'
  patch '/recipes/:id', to: 'recipes#update'
  put '/recipes/:id', to: 'recipes#update'
  delete '/recipes/:id', to: 'recipes#destroy'

  get '/signup', to: 'chefs#new'
  # Because the chef creation is managed by the signup page
  resources :chefs, except: [:new]

  # Routes for login
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  # Routes for ingredient
  # They cannot be deleted, and can be modified only by admin users
  resources :ingredients, except: [:destroy]

  #nested route
  resources :recipes do
    resources :comments, only: [:create]
  #post '/recipe/:id/comments', to: "comments#create", as: "recipe_comments"
  end

  post '/recipe/:id/like', to: "recipes#like", as: "like_recipe"

  # Route for ActionCable server
  mount ActionCable.server => '/cable'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 30}
  validates :description, presence: true, length: {minimum: 10, maximum: 255}
  validates :chef_id, presence: true
  # set the default order: 1st displayed is the last updated
  default_scope -> { order(updated_at: :desc)}
  belongs_to :chef
  # Following 2 lines are needed to create the association between Recipes and Ingredients
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  # Association with comments, if recipe is deleted, its comment are deleted as well
  has_many :comments, dependent: :destroy
  # keep track of like/dislike
  has_many :likes, dependent: :destroy

  # to associate image to recipe using uploader
  mount_uploader :image, ImageUploader

  # Functions to compute number of like/dislike
  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size    
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
  # To show a recipes and a list of all recipes, must be a logged user
  before_action :require_user, except: [:index, :show, :like]
  # To modify and delete a recipe must be the user whho has created it before
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user_like, only: [:like]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def show
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe deleted successfully"
    redirect_to recipes_path
  end

  def like
    like = Like.create(like: params[:like], chef: current_chef, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was succesful"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
    end
  end

  private
    def recipe_params
      # Allow to get as parameter a list of that are linked to the recipe from its creation
      params.require(:recipe).permit(:name, :description, :image, ingredient_ids: [])
    end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def require_same_user
      if current_chef != @recipe.chef && !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to recipes_path
      end  
    end

    def require_user_like
      if !logged_in?
        flash[:danger] = "You must be logged in to perform that action"
        redirect_to :back
      end
    end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="col-md-12">
    <!-- Multipart true means form contains non-ASCII files, images in this case -->
    <%= form_for(@recipe, :html => {class: "form-horizontal", multipart: true, role: "form"}) do |f| %>
      <div class="form-group">
        <div class="center">
          <%= f.label :name %>
        </div>
        <div class="col-md-4 col-md-offset-4 center">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="center">
          <%= f.label :description %>
        </div>
        <div class="col-md-6 col-md-offset-3">
          <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <hr />

      <!-- This form member is used to provide all ingredients as a checkbox list in order to bind them to a recipe -->
      <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8 center">
            <!-- bind checkboxes to ingredients and display the name -->
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text.capitalize} %>
            <% end %>
          </div>
        </div>
      </div>
      <hr />
      <!-- form group to upload image -->
      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-4">
          <%= f.label :image, "Add Image" %>
        </div>
        <div class="col-md-6">
          <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
        </div>
      </div>

      <br>
      <div class="form-group">
        <div class="center">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="center colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size: 130) %>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: |<%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize %> | 
        <%= pluralize(recipe.comments.count, 'Comment') %></small></small></span>
      </p>
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit this recipe", recipe_edit_path(recipe), class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete,
                        data: { confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>

      <!-- Display like/dislike -->
      <div class="row">
        <div class="pull-right liking">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> 
          <% end %> <%= recipe.thumbs_up_total %> || 
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>
          <% end %> <%= recipe.thumbs_down_total %>
        </div>
      </div>

    </div>
    <!-- to display image, if any -->
    <div class="col-md-2">
      <%= image_tag(recipe.image.url, size: "150x100") if recipe.image? %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/set_title', title: "Edit an existing recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/set_title', title: "Showing all recipes" %>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/set_title', title: "create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/set_title', title: @recipe.name %>

<div class="well col-md-8 col-md-offset-2">
  <!-- to display image, if any -->
  <div align="center">
    <%= image_tag @recipe.image.url if @recipe.image? %>
  </div>
  
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr />
  <%= simple_format(@recipe.description) %>
  <hr />
  <!-- To display the ingredients used for the shown recipe, if any -->
  <% if @recipe.ingredients.any? %>
    <p>Ingredients: <%= render @recipe.ingredients %></p>
  <% end %>

  <div class="recipe-actions">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
      <%= link_to "Edit this recipe", recipe_edit_path(@recipe), class: 'btn btn-xs btn-warning' %>
      <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete,
                                      data: { confirm: "Are you sure you want to delete?" },
                                      class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary" %>
  </div>  

  <!-- like/dislike view -->
  <br>
  <div class="row">
    <div class="col-md-8">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> 
        <% end %> <%= @recipe.thumbs_up_total %> || 
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i>
        <% end %> <%= @recipe.thumbs_down_total %>
    </div>
  </div>

    <div class="pull-right">
      <p class="center">
        <em>Created by:</em>
      </p>
      <p class="center">
        <!-- Image it's a link for the chef who has created that recipe -->
        <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
      </p>
      <p class="center">
        <small><%= @recipe.chef.chefname.capitalize %></small>
        <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
      </p>
    </div>
  </div>
</div>

<% if @recipe.comments.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
      <hr />
        <div>
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>

<!-- Add new comment -->
<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr />
      <!-- remote: true just submit the form and don't refresh the page (AJAX) -->
      <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description, "Comment" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter Comment Here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
      <% end %>
      <hr />
    </div>
  </div>
<% end %>

  